services:
  - type: web
    name: my-node-app
    env: node
    plan: free
    buildCommand: |
      rm -rf node_modules
      npm install
      npm rebuild bcrypt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
