services:
  - type: web
    name: my-node-app
    env: node
    plan: free
    buildCommand: |
      npm install
      npm rebuild bcrypt --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
